apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: site2-certificate
spec:
  secretName: site2-tls-secret
  issuerRef:
    name: letsencrypt-prod
  commonName: site2.shananadevops.xyz
  dnsNames:
    - site2.shananadevops.xyz
