apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: site1-certificate
spec:
  secretName: site1-tls-secret
  issuerRef:
    name: letsencrypt-prod
  commonName: site1.shananadevops.xyz
  dnsNames:
    - site1.shananadevops.xyz
