apiVersion: v1
kind: Service
metadata:
  name: ClusterIP
spec:
  selector:
    app: sample-app   # Replace 'sample-app' with the label used in the pods you want to expose
  ports:
    - protocol: TCP
      port: 80         # Port on the service
      targetPort: 8080 # Port on the pods
