apiVersion: v1
kind: Pod
metadata:
  name: pod-with-init-container
spec:
  containers:
    - name: main-app
      image: nginx:latest
      ports:
        - containerPort: 80
  initContainers:
    - name: init-config
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - echo "Initializing configuration..." > /app/config/config.txt;
      volumeMounts:
        - name: config-volume
          mountPath: /app/config
  volumes:
    - name: config-volume
      emptyDir: {}
