apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
spec:
  containers:
    - name: app-container
      image: kodekloud/simple-webapp-mysql
      envFrom: # get all the env from this secret file
        - secretRef:
            name: db-secret
