apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-hostpath-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # since it is not created dynamically
  hostPath:
    path: /path/on/host # Specify the path on the host machine


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-hostpath-pvc
spec:
  accessModes:
    - ReadWriteOnce  # only one node can access it
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi # Request 1 GiB of storage from the hostPath PV

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        volumeMounts:
        - name: my-volume
          mountPath: /data  # Specify the mount path in the container
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: example-hostpath-pvc  # Reference the PVC created earlier

