apiVersion: v1
kind: Service
metadata:
  name: NodePort-svc
spec:
  selector:
    app: your-app-label   # Replace 'your-app-label' with the label used in the pods you want to expose
  ports:
    - protocol: TCP
      port: 80             # Port on the service
      targetPort: 8080     # Port on the pods
  type: NodePort
  nodePort: 30001         # The NodePort value you want to use (30000 - 32767)
