apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
  namespace: your-namespace
spec:
  limits:
  - type: Container
    max:
      cpu: "1"
      memory: 512Mi
    min:
      cpu: "100m"
      memory: 50Mi
    default:
      cpu: "500m"
      memory: 256Mi
    defaultRequest:
      cpu: "200m"
      memory: 100Mi
    maxLimitRequestRatio:
      cpu: "10"
      memory: "4"
