apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: sample-container
    image: your-container-image:latest
    resources:
      requests:
        memory: "4Gi"
        cpu: "1"
      limits:
        memory: "5Gi"
        cpu: "2"