apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
  tolerations:
    - key: app
      operator: Equal
      value: web
      effect: NoSchedule