apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: my-namespace
data:
  database-url: "mysql://username:password@db-host:3306/mydb"
  api-key: "my-secret-api-key"
  app-config: |  # to add complex data like a dictionary
    {
      "debug": true,
      "logLevel": "info",
      "maxConnections": 100
    }
