apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
  namespace: my-namespace
spec:
  containers:
    - name: app-container
      image: nginx:latest
      env:
        - name: MY_USERNAME
          valueFrom:
            configMapKeyRef:
              name: my-secret
              key: username
        - name: MY_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: my-secret
              key: password
